nnrestapi:
  accessGroups:
    apiUsers: be_users[david,tanja],fe_users[3]

routeEnhancers:
  Nnrestapi:
    type: NnrestapiEnhancer
    routePath: '/api/{controller}/{action}/{uid}/{param1}/{param2}/{param3}'
    limitToPageType: 20210904
    defaults:
      controller: index
      action: index
      uid: ''
      param1: ''
      param2: ''
      param3: ''
    requirements:
      controller: '[^/]++'
      action: '[^/]*'
      uid: '[^/]*'
      param1: '[^/]*'
      param2: '[^/]*'
      param3: '[^/]*'
    _arguments:
      controller: controller
      action: action
      uid: uid
      param1: param1
      param2: param2
      param3: param3
