services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Nng\Nnrestapi\Middleware\:
    resource: '../Classes/Middleware/*'
    autowire: true
    autoconfigure: true
    public: true