services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Nng\Nnrestapi\Middleware\:
    resource: '../Classes/Middleware/*'
    autowire: true
    autoconfigure: true
    public: true

  Nng\Nnrestapi\:
    resource: '../Classes/*'
    exclude: 
      - '../Classes/Domain/Model/*'
      - '../Classes/Utilities/nnrest.php'

  Nng\Nnrestapi\Controller\ModController:
    tags: ['backend.controller']